# Usa la imagen base de Node.js versión 14
FROM node:14

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de configuración de npm al directorio de trabajo del contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todos los archivos del proyecto al directorio de trabajo del contenedor
COPY . .

# Expone el puerto 5000 para acceder a la aplicación
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["node", "server.js"]
